version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: kit
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X github.com/klytics/m365kit/cmd/version.Version={{.Version}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

brews:
  - repository:
      owner: klytics
      name: homebrew-tap
    homepage: "https://github.com/klytics/m365kit"
    description: "AI-native CLI for Microsoft 365 documents"
    license: "MIT"
